language: go

go:
  - 1.12.x

notifications:
  email: false

script:
  - go test -v ./cmd -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN